<?php

namespace Database\Seeders;

use App\Models\FinancialStatementTemplate;
use App\Models\FinancialStatementTemplateLine;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class FinancialStatementTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
        $this->seedBalanceSheetTemplate();
        $this->seedIncomeStatementNatureTemplate();
        $this->seedIncomeStatementFunctionTemplate();
    }

    protected function seedBalanceSheetTemplate(): void {
        $template = FinancialStatementTemplate::updateOrCreate(
            ['code' => 'BALANCE_SHEET'],
            [
                'name'           => 'Estado de Situación Financiera (Balance General)',
                'statement_type' => 'BALANCE_SHEET',
                'description'    => 'Estructura oficial normalizada según el Plan Contable General Empresarial (PCGE).',
                'is_active'      => true,
            ]
        );

        $lines = [
            // ACTIVO CORRIENTE
            [
                'line_code'     => 'ACT_CORR_HDR',
                'line_name'     => 'ACTIVO CORRIENTE',
                'line_type'     => 'HEADER',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 10,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'ACT_DISP',
                'line_name'     => 'Efectivo y Equivalentes de Efectivo',
                'line_type'     => 'ITEM',
                'account_range' => '10',
                'polarity'      => 'ADD',
                'sort_order'    => 20,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_COB_COM',
                'line_name'     => 'Cuentas por Cobrar Comerciales - Terceros y Relacionadas',
                'line_type'     => 'ITEM',
                'account_range' => '12, 13',
                'polarity'      => 'ADD',
                'sort_order'    => 30,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_OTR_COB',
                'line_name'     => 'Otras Cuentas por Cobrar',
                'line_type'     => 'ITEM',
                'account_range' => '14, 16, 17',
                'polarity'      => 'ADD',
                'sort_order'    => 40,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_INV',
                'line_name'     => 'Inventarios y Mercaderías',
                'line_type'     => 'ITEM',
                'account_range' => '20, 21, 23, 24, 25, 26, 28',
                'polarity'      => 'ADD',
                'sort_order'    => 50,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_INV_DESV',
                'line_name'     => '(-) Desvalorización de Inventarios',
                'line_type'     => 'ITEM',
                'account_range' => '29',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 60,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_ANT',
                'line_name'     => 'Servicios y Otros Contratados por Anticipado',
                'line_type'     => 'ITEM',
                'account_range' => '18',
                'polarity'      => 'ADD',
                'sort_order'    => 70,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'TOTAL_ACT_CORR',
                'line_name'     => 'TOTAL ACTIVO CORRIENTE',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 80,
                'level'         => 1,
                'is_bold'       => true,
            ],

            // ACTIVO NO CORRIENTE
            [
                'line_code'     => 'ACT_NO_CORR_HDR',
                'line_name'     => 'ACTIVO NO CORRIENTE',
                'line_type'     => 'HEADER',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 90,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'ACT_PPE',
                'line_name'     => 'Propiedades, Planta y Equipo',
                'line_type'     => 'ITEM',
                'account_range' => '33',
                'polarity'      => 'ADD',
                'sort_order'    => 100,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_BIO',
                'line_name'     => 'Activos Biológicos (Cultivos en desarrollo / Ganado)',
                'line_type'     => 'ITEM',
                'account_range' => '35',
                'polarity'      => 'ADD',
                'sort_order'    => 110,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_INT',
                'line_name'     => 'Intangibles',
                'line_type'     => 'ITEM',
                'account_range' => '34',
                'polarity'      => 'ADD',
                'sort_order'    => 120,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_DEP_ACUM',
                'line_name'     => '(-) Depreciación y Amortización Acumulada',
                'line_type'     => 'ITEM',
                'account_range' => '39',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 130,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'ACT_OTR_NO_CORR',
                'line_name'     => 'Otros Activos No Corrientes e Inversiones',
                'line_type'     => 'ITEM',
                'account_range' => '30, 31, 32, 36, 37, 38',
                'polarity'      => 'ADD',
                'sort_order'    => 140,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'TOTAL_ACT_NO_CORR',
                'line_name'     => 'TOTAL ACTIVO NO CORRIENTE',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 150,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'TOTAL_ACTIVO',
                'line_name'     => 'TOTAL ACTIVO',
                'line_type'     => 'TOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 160,
                'level'         => 1,
                'is_bold'       => true,
            ],

            // PASIVO CORRIENTE
            [
                'line_code'     => 'PAS_CORR_HDR',
                'line_name'     => 'PASIVO CORRIENTE',
                'line_type'     => 'HEADER',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 170,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'PAS_TRIB',
                'line_name'     => 'Tributos y Aportes al Sistema de Pensiones y Salud',
                'line_type'     => 'ITEM',
                'account_range' => '40',
                'polarity'      => 'ADD',
                'sort_order'    => 180,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAS_REM',
                'line_name'     => 'Remuneraciones y Participaciones por Pagar',
                'line_type'     => 'ITEM',
                'account_range' => '41',
                'polarity'      => 'ADD',
                'sort_order'    => 190,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAS_PAG_COM',
                'line_name'     => 'Cuentas por Pagar Comerciales - Terceros y Relacionadas',
                'line_type'     => 'ITEM',
                'account_range' => '42, 43',
                'polarity'      => 'ADD',
                'sort_order'    => 200,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAS_OBL_FIN',
                'line_name'     => 'Obligaciones Financieras Corrientes',
                'line_type'     => 'ITEM',
                'account_range' => '45',
                'polarity'      => 'ADD',
                'sort_order'    => 210,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAS_OTR_DIV',
                'line_name'     => 'Cuentas por Pagar Diversas y Provisiones',
                'line_type'     => 'ITEM',
                'account_range' => '44, 46, 47, 48',
                'polarity'      => 'ADD',
                'sort_order'    => 220,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'TOTAL_PAS_CORR',
                'line_name'     => 'TOTAL PASIVO CORRIENTE',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 230,
                'level'         => 1,
                'is_bold'       => true,
            ],

            // PASIVO NO CORRIENTE
            [
                'line_code'     => 'PAS_NO_CORR_HDR',
                'line_name'     => 'PASIVO NO CORRIENTE',
                'line_type'     => 'HEADER',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 240,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'PAS_DEUDA_LP',
                'line_name'     => 'Deudas a Largo Plazo y Otras Obligaciones',
                'line_type'     => 'ITEM',
                'account_range' => '49',
                'polarity'      => 'ADD',
                'sort_order'    => 250,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'TOTAL_PAS_NO_CORR',
                'line_name'     => 'TOTAL PASIVO NO CORRIENTE',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 260,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'TOTAL_PASIVO',
                'line_name'     => 'TOTAL PASIVO',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 270,
                'level'         => 1,
                'is_bold'       => true,
            ],

            // PATRIMONIO NETO
            [
                'line_code'     => 'PAT_HDR',
                'line_name'     => 'PATRIMONIO NETO',
                'line_type'     => 'HEADER',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 280,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'PAT_CAPITAL',
                'line_name'     => 'Capital Social / Institucional',
                'line_type'     => 'ITEM',
                'account_range' => '50',
                'polarity'      => 'ADD',
                'sort_order'    => 290,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAT_RESERVAS',
                'line_name'     => 'Reservas',
                'line_type'     => 'ITEM',
                'account_range' => '58',
                'polarity'      => 'ADD',
                'sort_order'    => 300,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'PAT_RES_ACUM',
                'line_name'     => 'Resultados Acumulados',
                'line_type'     => 'ITEM',
                'account_range' => '59',
                'polarity'      => 'ADD',
                'sort_order'    => 310,
                'level'         => 2,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'RESULTADO_EJERCICIO',
                'line_name'     => 'Resultado Neto del Ejercicio',
                'line_type'     => 'ITEM',
                'account_range' => '89', // Dynamic or closed to 89
                'polarity'      => 'ADD',
                'sort_order'    => 320,
                'level'         => 2,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'TOTAL_PATRIMONIO',
                'line_name'     => 'TOTAL PATRIMONIO NETO',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 330,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'TOTAL_PASIVO_PATRIMONIO',
                'line_name'     => 'TOTAL PASIVO Y PATRIMONIO NETO',
                'line_type'     => 'TOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 340,
                'level'         => 1,
                'is_bold'       => true,
            ],
        ];

        foreach ($lines as $data) {
            FinancialStatementTemplateLine::updateOrCreate(
                [
                    'template_id' => $template->id,
                    'line_code'   => $data['line_code'],
                ],
                $data
            );
        }
    }

    protected function seedIncomeStatementNatureTemplate(): void
    {
        $template = FinancialStatementTemplate::updateOrCreate(
            ['code' => 'INCOME_STATEMENT_NATURE'],
            [
                'name'           => 'Estado de Resultados por Naturaleza',
                'statement_type' => 'INCOME_STATEMENT_NATURE',
                'description'    => 'Agrupación económica por la naturaleza de los gastos e ingresos según el PCGE.',
                'is_active'      => true,
            ]
        );

        $lines = [
            [
                'line_code'     => 'NAT_VENTAS',
                'line_name'     => 'Ventas Netas de Bienes y Servicios',
                'line_type'     => 'ITEM',
                'account_range' => '70',
                'polarity'      => 'ADD',
                'sort_order'    => 10,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_VAR_PROD',
                'line_name'     => 'Variación de la Producción Almacenada',
                'line_type'     => 'ITEM',
                'account_range' => '71',
                'polarity'      => 'ADD',
                'sort_order'    => 20,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_PROD_ACTIVO',
                'line_name'     => 'Producción de Activo Inmovilizado',
                'line_type'     => 'ITEM',
                'account_range' => '72',
                'polarity'      => 'ADD',
                'sort_order'    => 30,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_COMPRAS',
                'line_name'     => '(-) Compras de Mercaderías y Materias Primas',
                'line_type'     => 'ITEM',
                'account_range' => '60, 69',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 40,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_VAR_EXIST',
                'line_name'     => '(+/-) Variación de Existencias',
                'line_type'     => 'ITEM',
                'account_range' => '61',
                'polarity'      => 'ADD',
                'sort_order'    => 50,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_MARGEN_COMERCIAL',
                'line_name'     => 'MARGEN COMERCIAL / VALOR AGREGADO BRUTO',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 60,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'NAT_SERVICIOS',
                'line_name'     => '(-) Gastos por Servicios Prestados por Terceros',
                'line_type'     => 'ITEM',
                'account_range' => '63',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 70,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_EXCEDENTE_BRUTO',
                'line_name'     => 'EXCEDENTE (INSUFICIENCIA) BRUTO DE EXPLOTACIÓN',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 80,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'NAT_PERSONAL',
                'line_name'     => '(-) Gastos de Personal y Directores',
                'line_type'     => 'ITEM',
                'account_range' => '62',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 90,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_TRIBUTOS',
                'line_name'     => '(-) Tributos y Cargas Impositivas de Explotación',
                'line_type'     => 'ITEM',
                'account_range' => '64',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 100,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_RES_EXPLOTACION',
                'line_name'     => 'RESULTADO DE EXPLOTACIÓN',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 110,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'NAT_DEPREC',
                'line_name'     => '(-) Valuación y Deterioro de Activos y Provisiones',
                'line_type'     => 'ITEM',
                'account_range' => '68',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 120,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_OTR_INGRESOS',
                'line_name'     => 'Otros Ingresos de Gestión',
                'line_type'     => 'ITEM',
                'account_range' => '75',
                'polarity'      => 'ADD',
                'sort_order'    => 130,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_OTR_GASTOS',
                'line_name'     => '(-) Otros Gastos de Gestión',
                'line_type'     => 'ITEM',
                'account_range' => '65, 94, 95',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 140,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_RES_OPERATIVO',
                'line_name'     => 'RESULTADO OPERATIVO',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 150,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'NAT_ING_FIN',
                'line_name'     => 'Ingresos Financieros',
                'line_type'     => 'ITEM',
                'account_range' => '77',
                'polarity'      => 'ADD',
                'sort_order'    => 160,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_GAS_FIN',
                'line_name'     => '(-) Gastos Financieros',
                'line_type'     => 'ITEM',
                'account_range' => '67',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 170,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_RES_ANTES_IMP',
                'line_name'     => 'RESULTADO ANTES DE IMPUESTO A LA RENTA',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 180,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'NAT_IMP_RENTA',
                'line_name'     => '(-) Impuesto a la Renta',
                'line_type'     => 'ITEM',
                'account_range' => '88',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 190,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'NAT_RES_NETO',
                'line_name'     => 'RESULTADO NETO DEL EJERCICIO',
                'line_type'     => 'TOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 200,
                'level'         => 1,
                'is_bold'       => true,
            ],
        ];

        foreach ($lines as $data) {
            FinancialStatementTemplateLine::updateOrCreate(
                [
                    'template_id' => $template->id,
                    'line_code'   => $data['line_code'],
                ],
                $data
            );
        }
    }

    protected function seedIncomeStatementFunctionTemplate(): void
    {
        $template = FinancialStatementTemplate::updateOrCreate(
            ['code' => 'INCOME_STATEMENT_FUNCTION'],
            [
                'name'           => 'Estado de Resultados por Función',
                'statement_type' => 'INCOME_STATEMENT_FUNCTION',
                'description'    => 'Agrupación funcional de costos y gastos por áreas (Ventas, Administración, Costo de Ventas).',
                'is_active'      => true,
            ]
        );

        $lines = [
            [
                'line_code'     => 'FUNC_VENTAS',
                'line_name'     => 'Ventas Netas (Ingresos Operacionales)',
                'line_type'     => 'ITEM',
                'account_range' => '70',
                'polarity'      => 'ADD',
                'sort_order'    => 10,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_COSTO_VENTAS',
                'line_name'     => '(-) Costo de Ventas',
                'line_type'     => 'ITEM',
                'account_range' => '69',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 20,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_UTILIDAD_BRUTA',
                'line_name'     => 'UTILIDAD (PÉRDIDA) BRUTA',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 30,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'FUNC_GASTOS_ADM',
                'line_name'     => '(-) Gastos de Administración',
                'line_type'     => 'ITEM',
                'account_range' => '94',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 40,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_GASTOS_VENTAS',
                'line_name'     => '(-) Gastos de Ventas',
                'line_type'     => 'ITEM',
                'account_range' => '95',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 50,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_UTILIDAD_OPERATIVA',
                'line_name'     => 'UTILIDAD (PÉRDIDA) OPERATIVA',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 60,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'FUNC_OTR_INGRESOS',
                'line_name'     => 'Otros Ingresos Operacionales',
                'line_type'     => 'ITEM',
                'account_range' => '75',
                'polarity'      => 'ADD',
                'sort_order'    => 70,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_OTR_GASTOS',
                'line_name'     => '(-) Otros Gastos Operacionales',
                'line_type'     => 'ITEM',
                'account_range' => '65',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 80,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_ING_FIN',
                'line_name'     => 'Ingresos Financieros',
                'line_type'     => 'ITEM',
                'account_range' => '77',
                'polarity'      => 'ADD',
                'sort_order'    => 90,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_GAS_FIN',
                'line_name'     => '(-) Gastos Financieros',
                'line_type'     => 'ITEM',
                'account_range' => '67',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 100,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_RES_ANTES_IMP',
                'line_name'     => 'RESULTADO ANTES DE IMPUESTO A LA RENTA',
                'line_type'     => 'SUBTOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 110,
                'level'         => 1,
                'is_bold'       => true,
            ],
            [
                'line_code'     => 'FUNC_IMP_RENTA',
                'line_name'     => '(-) Impuesto a la Renta',
                'line_type'     => 'ITEM',
                'account_range' => '88',
                'polarity'      => 'SUBTRACT',
                'sort_order'    => 120,
                'level'         => 1,
                'is_bold'       => false,
            ],
            [
                'line_code'     => 'FUNC_RES_NETO',
                'line_name'     => 'RESULTADO NETO DEL EJERCICIO',
                'line_type'     => 'TOTAL',
                'account_range' => null,
                'polarity'      => 'ADD',
                'sort_order'    => 130,
                'level'         => 1,
                'is_bold'       => true,
            ],
        ];

        foreach ($lines as $data) {
            FinancialStatementTemplateLine::updateOrCreate(
                [
                    'template_id' => $template->id,
                    'line_code'   => $data['line_code'],
                ],
                $data
            );
        }
    }
}
